# Generated by Django 5.0.7 on 2024-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lecturer_pictures/'),
        ),
    ]
