# Generated by Django 5.0.7 on 2024-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='attendance.CourseEnrollment', to='attendance.student'),
        ),
    ]
