# Generated by Django 5.0.7 on 2024-08-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='missed_students',
        ),
        migrations.AddField(
            model_name='attendancetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='staff_id',
            field=models.CharField(default='1001', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='11111', max_length=10, unique=True),
        ),
    ]
