# Generated by Django 5.0.7 on 2024-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_missed_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='staff_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
